In [1]:
!pip install --upgrade transformers
!pip install -q -U bitsandbytes
!pip install -q -U accelerate
!pip install peft
!pip install optuna
!pip install evaluate
!pip install mauve-text
!pip install bert_score
!pip install hf_xet

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.47.0)
Collecting transformers
  Downloading transformers-4.51.3-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.17.0)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers)
  Downloading huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2024.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.12.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->transformers) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->transformers) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->transformers) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->transformers) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->transformers) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->transformers) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.17->transformers) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.17->transformers) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.17->transformers) (2024.2.0)
Downloading transformers-4.51.3-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 64.8 MB/s eta 0:00:0000:010:01
Downloading huggingface_hub-0.30.2-py3-none-any.whl (481 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 481.4/481.4 kB 19.4 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.29.0
    Uninstalling huggingface-hub-0.29.0:
      Successfully uninstalled huggingface-hub-0.29.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.47.0
    Uninstalling transformers-4.47.0:
      Successfully uninstalled transformers-4.47.0
Successfully installed huggingface-hub-0.30.2 transformers-4.51.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 21.6 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.7/354.7 kB 6.1 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: peft in /usr/local/lib/python3.10/dist-packages (0.14.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from peft) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from peft) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from peft) (6.0.2)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.10/dist-packages (from peft) (2.5.1+cu121)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from peft) (4.51.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from peft) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from peft) (1.6.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.10/dist-packages (from peft) (0.4.5)
Requirement already satisfied: huggingface-hub>=0.25.0 in /usr/local/lib/python3.10/dist-packages (from peft) (0.30.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.0->peft) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.0->peft) (2024.12.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.0->peft) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.0->peft) (4.12.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->peft) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->peft) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->peft) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->peft) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->peft) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->peft) (2.4.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers->peft) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers->peft) (0.21.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.2)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.17->peft) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.17->peft) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.17->peft) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.17->peft) (2024.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.0->peft) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.0->peft) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.0->peft) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.0->peft) (2025.1.31)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.17->peft) (2024.2.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.10/dist-packages (4.2.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (1.14.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.10/dist-packages (from optuna) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.36)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (1.3.9)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy->optuna) (2.4.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->optuna) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->optuna) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy->optuna) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy->optuna) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy->optuna) (2024.2.0)
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.3.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.30.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (19.0.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.11.12)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->evaluate) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->evaluate) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->evaluate) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->evaluate) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->evaluate) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.17->evaluate) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.17->evaluate) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.17->evaluate) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.17->evaluate) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.17->evaluate) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.17->evaluate) (2024.2.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 2.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3
Collecting mauve-text
  Downloading mauve_text-0.4.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.10/dist-packages (from mauve-text) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.1 in /usr/local/lib/python3.10/dist-packages (from mauve-text) (1.2.2)
Collecting faiss-cpu>=1.7.0 (from mauve-text)
  Downloading faiss_cpu-1.10.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: tqdm>=4.40.0 in /usr/local/lib/python3.10/dist-packages (from mauve-text) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from mauve-text) (2.32.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from faiss-cpu>=1.7.0->mauve-text) (24.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.18.1->mauve-text) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.18.1->mauve-text) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.18.1->mauve-text) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.18.1->mauve-text) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.18.1->mauve-text) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.18.1->mauve-text) (2.4.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.1->mauve-text) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.1->mauve-text) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.1->mauve-text) (3.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->mauve-text) (3.4.1)

## load & import library

In [2]:
import time
import torch
import transformers
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments, Trainer
from peft import prepare_model_for_kbit_training, LoraConfig, PeftModel, get_peft_model
from datasets import load_dataset, Dataset
from accelerate import Accelerator
import pandas as pd
# from sklearn.model_selection import train_test_split
import os
import re
import pickle
import optuna
from optuna.pruners import MedianPruner
import copy
import json

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

In [3]:
# Muat model dan tokenizer DeepSeek
base_model_path = "/kaggle/input/deepseek-r1/transformers/deepseek-r1-distill-qwen-7b/2"

accelerator = Accelerator()
device = accelerator.device
print(device)

# Konfigurasi quantization
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=False,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

# Muat model dan tokenizer DeepSeek
base_model = AutoModelForCausalLM.from_pretrained(base_model_path, quantization_config=bnb_config, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(
    base_model_path,
    padding_side="left",
    device_map="auto",
    add_eos_token=True
)
tokenizer.pad_token = tokenizer.eos_token

cuda

Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

## load dataset

In [4]:
# Muat dataset

train_data = pd.read_parquet("/kaggle/input/writing-prompts/wp_train.parquet")
test_data = pd.read_parquet("/kaggle/input/writing-prompts/wp_test.parquet")
val_data = pd.read_parquet("/kaggle/input/writing-prompts/wp_valid.parquet")

train_dataset = Dataset.from_pandas(train_data.reset_index(drop=True))
val_dataset = Dataset.from_pandas(val_data.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_data.reset_index(drop=True))

In [5]:
# Tokenisasi dataset
def tokenize(prompt):
    result = tokenizer(
        prompt,
        truncation=True,
        max_length=512,
        padding="max_length",
    )
    result["labels"] = result["input_ids"].copy()
    return result

def generate_and_tokenize_prompt(data_point):
    full_prompt = f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
You are a creative writer specializing in short story writing. Generate a story based on the given details with minimum 1000 words.
    
### Input:
Story prompt (topic/idea): {data_point["prompt"]}
Story theme: {data_point["theme"]}

### Response:
{data_point["story"]}
"""
    return tokenize(full_prompt)

tokenized_train_dataset = train_dataset.map(generate_and_tokenize_prompt)
tokenized_val_dataset = val_dataset.map(generate_and_tokenize_prompt)
tokenized_test_dataset = test_dataset.map(generate_and_tokenize_prompt)

Map:   0%|          | 0/2080 [00:00<?, ? examples/s]

Map:   0%|          | 0/260 [00:00<?, ? examples/s]

Map:   0%|          | 0/260 [00:00<?, ? examples/s]

In [6]:
print(tokenized_val_dataset[0])

{'prompt': '" There is nothing a psychotic serial killer can do that ca n\'t be topped by a completely sane parent "', 'story': 'I anticipate your judgment, reader, but I find solace in writing. Besides, who are you to condemn me? How can anyone truly grasp the weight of my actions? How can you possibly comprehend the depths of despair I plumbed? Until you\'ve witnessed your own child suffering, until your little girl looks to you with fading life in her eyes, you have no right to judge.\n\nPerhaps I should begin at the beginning. Allow me to offer some context. I apologize in advance for my clumsy prose; I was never much of a writer.\n\nMy daughter, Carrie, was nine years old. Like all daughters, she was perfect in my eyes. As a single father, I bore the burdens that come with the role. But Carrie, she was my world. She was the wellspring of my happiness. The news of her mother\'s pregnancy had almost driven me to suicide. And then her mother died in childbirth, nearly pushing me over the edge again. Nine years later, it seems almost unimaginable that I was ever that low. Carrie was perfection. She was my salvation.\n\nBut who truly cares, right? Certainly not fate. Nobody but me seemed to value my daughter. Nobody understood how she rescued me, a grown man teetering on the brink. Nobody noticed her innocent spirit, her inherent right to live. Nobody offered assistance when she desperately needed a kidney.\n\nIt happened so suddenly. The illness revealed itself first in her hair. I\'m not a doctor, so dismiss my observation as nonsense if you will, but I noticed it in her hair first. It became listless and sickly. You know the look of unhealthy hair; it\'s subtle, yet unmistakably striking. I saw the change in her hair, and soon after, she developed a fever and complained of pain. Her kidneys were failing. Blame my genes for that cruel twist of fate.\n\nThe hospital staff did everything they could, but it soon became clear that Carrie\'s time was running out. There was little they could do beyond supportive care. She needed a kidney transplant. The waiting list was tragically long, and her deteriorating condition placed her at the bottom. Nobody seemed to care that she deserved to live, deserved a chance. Nobody gave her a second thought.\n\nFor the first time since her birth, I considered ending my own life. I\'m weak in that way, I suppose. But Carrie was still alive, and I refused to taint her final days with my death. As agonizing as it was, I had to be there for her. But it was a constant struggle. Her condition worsened, and I brought her home to be in a more comforting environment. I hired a live-in nurse, to hell with my retirement savings.\n\nTime passed in a haze of despair. Carrie\'s life force slowly ebbed away, and she spent most of her time unconscious. My own mental state deteriorated, and I descended into a dark abyss. I desperately tried everything: praying to God, exploring alternative medicines, throwing money at anyone who claimed they could help, even if they were obvious charlatans.\n\nFinally, a glimmer of hope emerged from the darkness. I encountered a back-alley doctor. His name was Goldman, or at least that\'s what he told me. I found him on the dark web, a digital underworld rife with illegal drugs and other unsavory dealings. I knew nothing about computers and hated the entire process, but I was desperate. I\'m eternally grateful that I persevered.\n\nGoldman was a surgeon, and reportedly a highly skilled one at that. However, he was consumed by greed and obsessed with money. He practiced his trade illegally and without any regard for ethics or morality. He claimed he could save Carrie. All he needed was a kidney.\n\n"You\'re wasting my time," I retorted. "Any doctor could save her if we had a kidney. That\'s the problem."\n\nAnd that\'s where Goldman was different. "You strike me as a man who would do anything to save his daughter," he said, his eyes glinting with an unsettling intensity. "Anything. You\'d be worse than a psycho."\n\nThe nurse, whose name was Angela, was the first person I approached for testing. I told her it was in case Carrie needed a blood transfusion. I paid her handsomely for her cooperation, and she agreed readily, having grown fond of Carrie during her time in our home. She was aware that Carrie was nearing the end, but she was eager to help in any way she could.\n\n"Of course, I\'d donate blood if she needs it," she said with a gentle smile. "So we went to Goldman and maybe it was some divine intervention. The nurse was a perfect match.\n\nI took Angela out to dinner and showered her with gifts. I treated her better than I had ever treated anyone in my life.\n\n"Why are you doing this, Mr. Dancer?" she asked, her eyes filled with genuine confusion.\n\n"To thank you for being Carrie\'s blood donor. In case she ever needs blood, you\'ll be there. It would takes a load off my mind."\n\n"But you don\'t have to thank me so lavishly," she protested. "She\'s a sweet girl. I\'ll do anything for her to get better."\n\nSo you see? I manipulated her.\n\nThat night, I made sure Carrie was sound asleep, locking her door for added security. When Angela was also asleep, I crept into her room. She was sleeping without any clothes and she was an attractive woman. In that moment, a fleeting vision flashed before my eyes: a future where Angela and I were married, where she became Carrie\'s new mother, where she had willingly donated her kidney to save her life. A wave of profound sadness washed over me, knowing that this future would never exist. Carrie didn\'t have time for dreams. Angela wouldn\'t get that.\n\nI suffocated Angela slightly and then tied her up. Her face contorted in a mask of terror, and I quickly gagged her with a cloth. What did she think I was going to do? Rape her? I am not such a monster, no matter what they call me.\n\nGoldman arrived later that night and meticulously outlined my next steps. "I will assist, but I will not kill," he declared, emphasizing his own moral limitations. He was motivated solely by money, the greedy bastard. I had to do the dirty work myself.\n\nSo I killed the nurse. It was messy and brutal, and I can only imagine the pain she endured. Her death was prolonged, and I carry the burden of that regret to this day. But her kidney was successfully harvested, and I roused Carrie from her sleep after removing the blood-stained raincoat.\n\nTime was of the essence, so we raced to Goldman\'s makeshift operating room located in a grimy back alley. Rats scattered as we approached the door. I carried my frail daughter in my arms and desperately prayed for forgiveness and for her life.\n\nThe surgery was a success, and Carrie miraculously recovered from the brink of death.\n\nI buried Angela\'s body deep in the woods, and severed all ties with Goldman.\n\nA year has now passed. Carrie is ten years old, soon to turn eleven. She walks, plays, and exudes the innocent joy that had been stolen from her. Nobody has come looking for Angela. I suspect she was like me, alone in this world, without family or friends to notice her absence.\n\nSometimes I am haunted by Angela, by the life that could have been. She could have been my wife, and we could have been a complete family. But that was always a delusion. Carrie is real, and she is everything to me.\n\nI know you will judge me. Go ahead. If it helps you sleep at night, if it validates your own sense of moral superiority, then judge away.\n\nBut know this: you have never seen my daughter. You have never witnessed the desperation in her sick, pleading eyes. You have never stood on the precipice of despair, facing the imminent loss of your child. For Carrie\'s death would have surely been my death as well.\n\nJudge me if you must. But I watch her run and play, vibrant and full of life. To me, it was a worthwhile decision. A decision that i\'m proud of.', 'theme': 'loss of innocence', 'input_ids': [151646, 38214, 374, 458, 7600, 429, 16555, 264, 3383, 11, 34426, 448, 458, 1946, 429, 5707, 4623, 2266, 13, 9645, 264, 2033, 429, 34901, 44595, 279, 1681, 382, 14374, 29051, 510, 2610, 525, 264, 11521, 6916, 57294, 304, 2805, 3364, 4378, 13, 19813, 264, 3364, 3118, 389, 279, 2661, 3565, 448, 8028, 220, 16, 15, 15, 15, 4244, 624, 1066, 14374, 5571, 510, 17938, 9934, 320, 16411, 14, 41777, 1648, 330, 2619, 374, 4302, 264, 93141, 6146, 24518, 646, 653, 429, 2162, 308, 944, 387, 39801, 553, 264, 6587, 61100, 2681, 6228, 17938, 6912, 25, 4709, 315, 56211, 271, 14374, 5949, 510, 40, 47148, 697, 19407, 11, 6604, 11, 714, 358, 1477, 2048, 578, 304, 4378, 13, 30809, 11, 879, 525, 498, 311, 38974, 752, 30, 2585, 646, 5489, 9428, 33377, 279, 4680, 315, 847, 6168, 30, 2585, 646, 498, 10767, 57289, 279, 42857, 315, 45896, 358, 41172, 2721, 30, 28970, 498, 3003, 31026, 697, 1828, 1682, 15691, 11, 3080, 697, 2632, 3743, 5868, 311, 498, 448, 58517, 2272, 304, 1059, 6414, 11, 498, 614, 902, 1290, 311, 11651, 382, 31476, 358, 1265, 3161, 518, 279, 7167, 13, 26530, 752, 311, 3010, 1045, 2266, 13, 358, 36879, 304, 11912, 369, 847, 93218, 60701, 26, 358, 572, 2581, 1753, 315, 264, 6916, 382, 5050, 9803, 11, 64451, 11, 572, 11627, 1635, 2310, 13, 8909, 678, 29868, 11, 1340, 572, 4727, 304, 847, 6414, 13, 1634, 264, 3175, 6981, 11, 358, 38686, 279, 62974, 429, 2525, 448, 279, 3476, 13, 1988, 64451, 11, 1340, 572, 847, 1879, 13, 2932, 572, 279, 1632, 29223, 315, 847, 23009, 13, 576, 3669, 315, 1059, 6554, 594, 19636, 1030, 4558, 16227, 752, 311, 18144, 13, 1597, 1221, 1059, 6554, 8469, 304, 96194, 11, 7009, 17461, 752, 916, 279, 6821, 1549, 13, 37066, 1635, 2937, 11, 432, 4977, 4558, 86112, 480, 429, 358, 572, 3512, 429, 3347, 13, 64451, 572, 38043, 13, 2932, 572, 847, 44935, 382, 3983, 879, 9428, 33572, 11, 1290, 30, 52366, 537, 24382, 13, 36458, 714, 752, 9324, 311, 897, 847, 9803, 13, 36458, 15985, 1246, 1340, 44333, 752, 11, 264, 14700, 883, 1013, 1404, 287, 389, 279, 67115, 13, 36458, 13686, 1059, 24243, 8913, 11, 1059, 36988, 1290, 311, 3887, 13, 36458, 8900, 12994, 979, 1340, 37543, 4362, 264, 37942, 382, 2132, 6932, 773, 14843, 13, 576, 17125, 10457, 5086, 1156, 304, 1059, 6869, 13, 358, 2776, 537, 264, 10668, 11, 773, 13432, 847, 21930, 438, 40802, 421, 498, 686, 11, 714, 358, 13686, 432, 304, 1059, 6869, 1156, 13, 1084, 6116, 1140, 1717, 323, 14036, 398, 13, 1446, 1414, 279, 1401, 315, 52708, 6869, 26, 432, 594, 26447, 11, 3602, 95107, 2845, 21239, 13, 358, 5485, 279, 2297, 304, 1059, 6869, 11, 323, 5135, 1283, 11, 1340, 7881, 264, 33553, 323, 33970, 315, 6646, 13, 6252, 80860, 1033, 21394, 13, 2502, 373, 847, 20727, 369, 429, 27030, 26646, 315, 24382, 382, 785, 8777, 5570, 1521, 4297, 807, 1410, 11, 714, 432, 5135, 6116, 2797, 429, 64451, 594, 882, 572, 4303, 700, 13, 2619, 572, 2632, 807, 1410, 653, 7797, 32345, 2453, 13, 151643], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [151646, 38214, 374, 458, 7600, 429, 16555, 264, 3383, 11, 34426, 448, 458, 1946, 429, 5707, 4623, 2266, 13, 9645, 264, 2033, 429, 34901, 44595, 279, 1681, 382, 14374, 29051, 510, 2610, 525, 264, 11521, 6916, 57294, 304, 2805, 3364, 4378, 13, 19813, 264, 3364, 3118, 389, 279, 2661, 3565, 448, 8028, 220, 16, 15, 15, 15, 4244, 624, 1066, 14374, 5571, 510, 17938, 9934, 320, 16411, 14, 41777, 1648, 330, 2619, 374, 4302, 264, 93141, 6146, 24518, 646, 653, 429, 2162, 308, 944, 387, 39801, 553, 264, 6587, 61100, 2681, 6228, 17938, 6912, 25, 4709, 315, 56211, 271, 14374, 5949, 510, 40, 47148, 697, 19407, 11, 6604, 11, 714, 358, 1477, 2048, 578, 304, 4378, 13, 30809, 11, 879, 525, 498, 311, 38974, 752, 30, 2585, 646, 5489, 9428, 33377, 279, 4680, 315, 847, 6168, 30, 2585, 646, 498, 10767, 57289, 279, 42857, 315, 45896, 358, 41172, 2721, 30, 28970, 498, 3003, 31026, 697, 1828, 1682, 15691, 11, 3080, 697, 2632, 3743, 5868, 311, 498, 448, 58517, 2272, 304, 1059, 6414, 11, 498, 614, 902, 1290, 311, 11651, 382, 31476, 358, 1265, 3161, 518, 279, 7167, 13, 26530, 752, 311, 3010, 1045, 2266, 13, 358, 36879, 304, 11912, 369, 847, 93218, 60701, 26, 358, 572, 2581, 1753, 315, 264, 6916, 382, 5050, 9803, 11, 64451, 11, 572, 11627, 1635, 2310, 13, 8909, 678, 29868, 11, 1340, 572, 4727, 304, 847, 6414, 13, 1634, 264, 3175, 6981, 11, 358, 38686, 279, 62974, 429, 2525, 448, 279, 3476, 13, 1988, 64451, 11, 1340, 572, 847, 1879, 13, 2932, 572, 279, 1632, 29223, 315, 847, 23009, 13, 576, 3669, 315, 1059, 6554, 594, 19636, 1030, 4558, 16227, 752, 311, 18144, 13, 1597, 1221, 1059, 6554, 8469, 304, 96194, 11, 7009, 17461, 752, 916, 279, 6821, 1549, 13, 37066, 1635, 2937, 11, 432, 4977, 4558, 86112, 480, 429, 358, 572, 3512, 429, 3347, 13, 64451, 572, 38043, 13, 2932, 572, 847, 44935, 382, 3983, 879, 9428, 33572, 11, 1290, 30, 52366, 537, 24382, 13, 36458, 714, 752, 9324, 311, 897, 847, 9803, 13, 36458, 15985, 1246, 1340, 44333, 752, 11, 264, 14700, 883, 1013, 1404, 287, 389, 279, 67115, 13, 36458, 13686, 1059, 24243, 8913, 11, 1059, 36988, 1290, 311, 3887, 13, 36458, 8900, 12994, 979, 1340, 37543, 4362, 264, 37942, 382, 2132, 6932, 773, 14843, 13, 576, 17125, 10457, 5086, 1156, 304, 1059, 6869, 13, 358, 2776, 537, 264, 10668, 11, 773, 13432, 847, 21930, 438, 40802, 421, 498, 686, 11, 714, 358, 13686, 432, 304, 1059, 6869, 1156, 13, 1084, 6116, 1140, 1717, 323, 14036, 398, 13, 1446, 1414, 279, 1401, 315, 52708, 6869, 26, 432, 594, 26447, 11, 3602, 95107, 2845, 21239, 13, 358, 5485, 279, 2297, 304, 1059, 6869, 11, 323, 5135, 1283, 11, 1340, 7881, 264, 33553, 323, 33970, 315, 6646, 13, 6252, 80860, 1033, 21394, 13, 2502, 373, 847, 20727, 369, 429, 27030, 26646, 315, 24382, 382, 785, 8777, 5570, 1521, 4297, 807, 1410, 11, 714, 432, 5135, 6116, 2797, 429, 64451, 594, 882, 572, 4303, 700, 13, 2619, 572, 2632, 807, 1410, 653, 7797, 32345, 2453, 13, 151643]}

### sampling

In [7]:
def balanced_sample(df, total_samples=52):
    theme_counts = df['theme'].value_counts()
    num_themes = len(theme_counts)
    samples_per_theme = total_samples // num_themes
    remainder = total_samples % num_themes

    sorted_themes = theme_counts.sort_values(ascending=False).index.tolist()

    sample_df = pd.DataFrame()
    for i, theme in enumerate(sorted_themes):
        n_samples = samples_per_theme + (1 if i < remainder else 0)
        theme_subset = df[df['theme'] == theme]

        if len(theme_subset) >= n_samples:
            sample = theme_subset.sample(n=n_samples, random_state=42)
        else:
            sample = theme_subset  # take all available if fewer than needed

        sample_df = pd.concat([sample_df, sample], ignore_index=True)

    return sample_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Apply balanced sampling to both val and test
sampled_val_df = balanced_sample(val_data, total_samples=52)
sampled_test_df = balanced_sample(test_data, total_samples=52)

# Convert to Hugging Face Datasets
sampled_val_dataset = Dataset.from_pandas(sampled_val_df)
sampled_test_dataset = Dataset.from_pandas(sampled_test_df)

# Tokenize
tokenized_sampled_val_dataset = sampled_val_dataset.map(generate_and_tokenize_prompt)
tokenized_sampled_test_dataset = sampled_test_dataset.map(generate_and_tokenize_prompt)

Map:   0%|          | 0/52 [00:00<?, ? examples/s]

Map:   0%|          | 0/52 [00:00<?, ? examples/s]

In [8]:
print(tokenized_sampled_val_dataset[0])

{'prompt': '" So, you do know why we called you down here right? "', 'story': 'Felix Bowman was wrestling with the final stages of a major project on a Tuesday afternoon that felt indistinguishable from any other in the fluorescent-lit purgatory of the office. This project, his first of such magnitude since the… incident, held a significance that far outweighed its face value. He actively fought to keep the incident buried, a dark secret entombed deep within the recesses of his mind. Yet, like a persistent weed pushing through cracked pavement, the memory would occasionally resurface, a stark reminder of the line he had crossed.\n\nHe took a deliberate sip of the lukewarm coffee that had long since lost its appeal, trying to anchor himself to the present. Focus, he told himself. He needed to concentrate on the task at hand. "Ah, yes… yes, that should work," he murmured, his voice barely audible above the hum of the office air conditioning. "Yes, that will do."\n\nHis internal monologue gradually faded as he became engrossed in the project, his mind lost in a labyrinth of data and calculations. He scribbled notes and muttered to himself, a habit his colleagues had grown accustomed to. The quiet murmur was a sign that Felix was productive, on the cusp of a breakthrough. It was the unnerving silence that signaled something was amiss, a silent alarm that put them on edge. They learned early on to grant him his space during those introspective periods.\n\nHe was deep in concentration, a fragile train of thought rapidly gaining momentum, when the familiar *ping* of a new email intruded upon his focus. He resisted the urge to immediately check it, clinging desperately to the thread of his idea. Someone always wanted something. It was a constant barrage of requests and demands, a relentless tide pulling him under. The casual "hello" or the spontaneous "join us for lunch" seemed like relics of a bygone era, a time when genuine connection wasn\'t mediated by digital devices.\n\nFinally, the train of thought reached its destination, the idea crystallized. He reluctantly turned his attention to the computer screen, the notification icon blinking obnoxiously in the corner. The email was from downstairs. And communications originating from "downstairs" rarely carried good news. They wanted to see him. Immediately. The urgency was palpable. Of course it was important, he thought with a touch of cynicism. It was *always* important when it came from the shadowy depths of the lower levels.\n\nHe pushed himself up from his chair, his joints protesting from prolonged inactivity. He drained the last of his now-cold coffee, the bitter taste mirroring his apprehension. As he approached the elevators, he was greeted by a hastily written sign, scrawled in blue ink and taped to the doors: "Out of Order." Typical. He sighed and resigned himself to the stairs. Thirteen floors down, plus three below ground level. The very bottom. As low as one could go within this towering monument of concrete and steel.\n\nHe used to question why the upper management chose to locate their offices on the lowest levels. It seemed counterintuitive. But since the incident, he understood. He understood the symbolism, the deliberate intention of placing certain individuals in proximity to the metaphorical basement. He couldn’t shake the unsettling premonition that they were anticipating a repeat performance, and he hadn’t imagined it would be required so soon. Had it really only been a few weeks since the last… assignment? Maybe this was just how things were going to be now.\n\nHe finally reached the reception area outside the expansive boardroom and the offices of the senior executives. He informed the receptionist of his arrival, stating his name with a forced calmness. She simply nodded, her expression unreadable, and pressed a button on her phone.\n\n"Yes?" a deep, resonant voice boomed from the speaker.\n\n"Mr. Bowman is here, sir," she replied.\n\n"Put him in the boardroom, please. We\'re waiting on Mendez."\n\nShe offered no further explanation, her gaze fixed on him, her dark eyes seeming to penetrate his very soul, seeing things he wished remained hidden. The unspoken words hung heavy in the air.\n\nThe boardroom was vast and impersonal, dominated by a massive mahogany table that stretched seemingly to the far end of the room. Tucked away in a corner, near a window overlooking a bleak concrete courtyard, was a smaller table laden with bottles of water, fresh fruit, and a small carafe of what appeared to be freshly brewed coffee. He chose a seat near the center of the large table, facing the door. He felt exposed, vulnerable under the scrutiny of an unseen audience.\n\nA clock on the wall behind him began to tick. Each tick seemed to grow louder, more insistent, amplifying the tension in the room. TICK. TICK. TICK. His nerves were on edge, stretched taut like piano wire. While he couldn’t be certain, he was fairly confident about the reason for his summons. TICK. TICK. TICK. *Damn that clock!* he thought, the urge to silence it almost overwhelming. He wanted to rip it from the wall, shatter it on the floor, anything to end its relentless, mocking rhythm.\n\nHe heard voices outside the door. Mendez had arrived. He could see three distinct shadows shifting behind the frosted glass pane adjacent to the door. He caught snippets of polite conversation, hollow pleasantries that did nothing to soothe his escalating anxiety. *How lovely*, he thought sarcastically, the simmering desire to obliterate the clock still burning within him.\n\nThe door swung open, and Mendez, Palmer, and Wright entered the room. Felix rose to greet them, his movements stiff and unnatural. The men were all tall, imposing figures with the same unnervingly dark eyes as the receptionist, eyes that seemed to hold secrets he couldn\'t fathom.\n\n"Good afternoon, gentlemen," he said, forcing a smile as they took their seats across the table from him.\n\n"Yes, good afternoon, Mr. Bowman," said Palmer, his deep voice oddly soothing, a stark contrast to the tension that filled the room. "How are you progressing with your latest project?" he continued.\n\n"Good, sir. I\'m in the final stages of fact-checking and then I just need to finalize my report. It was a bit of a slow start, but I believe I\'ve arrived at something solid." He tried to sound confident, professional, but he could hear the tremor in his own voice.\n\n"Excellent, we can\'t wait to have a look," said Wright, offering a perfunctory smile. Mendez simply nodded in agreement, his gaze unwavering. Palmer opened a large manila folder, its contents hidden from view.\n\n"Now," Palmer said, his voice hardening, the soothing facade evaporating, "to get down to the business of the day." He leaned forward, his gaze fixed on Felix. "Do you know why we called you down here?"\n\nFelix\'s mouth suddenly felt dry, his throat constricted. He felt like he was suffocating, the room shrinking around him. TICK. TICK. TICK. The clock was booming in his ears now, a deafening percussion that threatened to shatter his sanity.\n\nHe cleared his throat, struggling to find his voice. "Yes," he managed to croak. "Yes, sir, I know why I\'m here. I know what you\'re going to ask me to do. I\'ve done it before, and I know I can do it again." He surprised himself with his own willingness. Or was it resignation?\n\nThe three men exchanged knowing glances. They nodded slowly, almost imperceptibly. "Good," was all they said.\n\nThey stood to leave, their business concluded. As Palmer reached the door, he paused and added, "His name is Terry Andrews. All the details are in the file on the table. Due date is October 27th." With that, they were gone, leaving Felix alone in the sterile silence of the boardroom.\n\nFelix sank back into his chair, releasing a slow, deliberate breath. The clock was still ticking, but the sound seemed muted, distant, almost as if it was mocking him softly now. He reached across the table and picked up the file, his fingers trembling slightly. He opened it, his heart pounding in his chest.\n\nTerry Andrews stared back at him from the page. It was a black and white photograph, grainy and indistinct, but the details were there: a round face, a gap-toothed grin, innocent eyes that belied the fate that awaited him. He glanced through the file, skimming the bureaucratic jargon, the cold, clinical assessments. Finally, he stopped at the first page and read the words he had been dreading.\n\nTerry Andrews, 7th birthday party. Theme: Monster-truck driving zombie pirate dinosaurs.\nYou get drunk at one Christmas party, come up with the worst idea ever, and it takes off." he muttered, collecting the file and heading out the door.', 'theme': 'honor turns to Dishonor.', 'input_ids': [151646, 38214, 374, 458, 7600, 429, 16555, 264, 3383, 11, 34426, 448, 458, 1946, 429, 5707, 4623, 2266, 13, 9645, 264, 2033, 429, 34901, 44595, 279, 1681, 382, 14374, 29051, 510, 2610, 525, 264, 11521, 6916, 57294, 304, 2805, 3364, 4378, 13, 19813, 264, 3364, 3118, 389, 279, 2661, 3565, 448, 8028, 220, 16, 15, 15, 15, 4244, 624, 1066, 14374, 5571, 510, 17938, 9934, 320, 16411, 14, 41777, 1648, 330, 2055, 11, 498, 653, 1414, 3170, 582, 2598, 498, 1495, 1588, 1290, 30, 6228, 17938, 6912, 25, 15669, 10577, 311, 48168, 54037, 382, 14374, 5949, 510, 37, 67718, 84596, 572, 35440, 448, 279, 1590, 17628, 315, 264, 3598, 2390, 389, 264, 7589, 13354, 429, 6476, 1257, 88647, 480, 504, 894, 1008, 304, 279, 73764, 2852, 275, 3999, 70, 5269, 315, 279, 5163, 13, 1096, 2390, 11, 806, 1156, 315, 1741, 25621, 2474, 279, 1940, 10455, 11, 5644, 264, 25361, 429, 3041, 61974, 291, 1181, 3579, 897, 13, 1260, 22040, 20463, 311, 2506, 279, 10455, 26918, 11, 264, 6319, 6234, 1197, 316, 2721, 5538, 2878, 279, 46762, 288, 315, 806, 3971, 13, 14626, 11, 1075, 264, 24999, 39375, 17461, 1526, 42839, 64342, 11, 279, 4938, 1035, 22930, 592, 10509, 11, 264, 37146, 26528, 315, 279, 1555, 566, 1030, 27031, 382, 1519, 3867, 264, 44972, 46615, 315, 279, 81280, 365, 2178, 10799, 429, 1030, 1293, 2474, 5558, 1181, 14303, 11, 4460, 311, 17105, 5561, 311, 279, 3042, 13, 25806, 11, 566, 3229, 5561, 13, 1260, 4362, 311, 36355, 389, 279, 3383, 518, 1424, 13, 330, 24765, 11, 9834, 1940, 9834, 11, 429, 1265, 975, 1335, 566, 86551, 3073, 11, 806, 7743, 19460, 79315, 3403, 279, 2784, 315, 279, 5163, 3720, 34021, 13, 330, 9454, 11, 429, 686, 653, 2217, 15986, 5306, 1615, 76728, 26024, 53334, 438, 566, 6116, 2922, 2128, 291, 304, 279, 2390, 11, 806, 3971, 5558, 304, 264, 98710, 315, 821, 323, 28117, 13, 1260, 67222, 6066, 832, 8388, 323, 86594, 311, 5561, 11, 264, 14132, 806, 17639, 1030, 14700, 52084, 311, 13, 576, 11340, 8146, 65106, 572, 264, 1841, 429, 55923, 572, 26236, 11, 389, 279, 272, 29763, 315, 264, 41345, 13, 1084, 572, 279, 16950, 19505, 21162, 429, 74748, 2494, 572, 1079, 1038, 11, 264, 21059, 16624, 429, 2182, 1105, 389, 6821, 13, 2379, 9498, 4124, 389, 311, 13198, 1435, 806, 3550, 2337, 1846, 25528, 9085, 18346, 382, 1519, 572, 5538, 304, 19950, 11, 264, 44250, 5426, 315, 3381, 18512, 29140, 23270, 11, 979, 279, 11285, 353, 9989, 9, 315, 264, 501, 2551, 10582, 37377, 5193, 806, 5244, 13, 1260, 66314, 279, 32047, 311, 7069, 1779, 432, 11, 96358, 37543, 311, 279, 4516, 315, 806, 4522, 13, 34172, 2677, 4829, 2494, 13, 1084, 572, 264, 6783, 80590, 315, 7388, 323, 18154, 11, 264, 59035, 41938, 22266, 1435, 1212, 13, 576, 16334, 330, 14990, 1, 476, 279, 53457, 330, 5987, 601, 369, 15786, 1, 9324, 1075, 98416, 315, 264, 553, 45596, 11385, 11, 264, 882, 979, 22011, 3633, 5710, 944, 77826, 553, 7377, 7611, 382, 23949, 11, 279, 5426, 315, 3381, 8643, 1181, 9106, 11, 279, 4522, 63468, 1506, 151643], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [151646, 38214, 374, 458, 7600, 429, 16555, 264, 3383, 11, 34426, 448, 458, 1946, 429, 5707, 4623, 2266, 13, 9645, 264, 2033, 429, 34901, 44595, 279, 1681, 382, 14374, 29051, 510, 2610, 525, 264, 11521, 6916, 57294, 304, 2805, 3364, 4378, 13, 19813, 264, 3364, 3118, 389, 279, 2661, 3565, 448, 8028, 220, 16, 15, 15, 15, 4244, 624, 1066, 14374, 5571, 510, 17938, 9934, 320, 16411, 14, 41777, 1648, 330, 2055, 11, 498, 653, 1414, 3170, 582, 2598, 498, 1495, 1588, 1290, 30, 6228, 17938, 6912, 25, 15669, 10577, 311, 48168, 54037, 382, 14374, 5949, 510, 37, 67718, 84596, 572, 35440, 448, 279, 1590, 17628, 315, 264, 3598, 2390, 389, 264, 7589, 13354, 429, 6476, 1257, 88647, 480, 504, 894, 1008, 304, 279, 73764, 2852, 275, 3999, 70, 5269, 315, 279, 5163, 13, 1096, 2390, 11, 806, 1156, 315, 1741, 25621, 2474, 279, 1940, 10455, 11, 5644, 264, 25361, 429, 3041, 61974, 291, 1181, 3579, 897, 13, 1260, 22040, 20463, 311, 2506, 279, 10455, 26918, 11, 264, 6319, 6234, 1197, 316, 2721, 5538, 2878, 279, 46762, 288, 315, 806, 3971, 13, 14626, 11, 1075, 264, 24999, 39375, 17461, 1526, 42839, 64342, 11, 279, 4938, 1035, 22930, 592, 10509, 11, 264, 37146, 26528, 315, 279, 1555, 566, 1030, 27031, 382, 1519, 3867, 264, 44972, 46615, 315, 279, 81280, 365, 2178, 10799, 429, 1030, 1293, 2474, 5558, 1181, 14303, 11, 4460, 311, 17105, 5561, 311, 279, 3042, 13, 25806, 11, 566, 3229, 5561, 13, 1260, 4362, 311, 36355, 389, 279, 3383, 518, 1424, 13, 330, 24765, 11, 9834, 1940, 9834, 11, 429, 1265, 975, 1335, 566, 86551, 3073, 11, 806, 7743, 19460, 79315, 3403, 279, 2784, 315, 279, 5163, 3720, 34021, 13, 330, 9454, 11, 429, 686, 653, 2217, 15986, 5306, 1615, 76728, 26024, 53334, 438, 566, 6116, 2922, 2128, 291, 304, 279, 2390, 11, 806, 3971, 5558, 304, 264, 98710, 315, 821, 323, 28117, 13, 1260, 67222, 6066, 832, 8388, 323, 86594, 311, 5561, 11, 264, 14132, 806, 17639, 1030, 14700, 52084, 311, 13, 576, 11340, 8146, 65106, 572, 264, 1841, 429, 55923, 572, 26236, 11, 389, 279, 272, 29763, 315, 264, 41345, 13, 1084, 572, 279, 16950, 19505, 21162, 429, 74748, 2494, 572, 1079, 1038, 11, 264, 21059, 16624, 429, 2182, 1105, 389, 6821, 13, 2379, 9498, 4124, 389, 311, 13198, 1435, 806, 3550, 2337, 1846, 25528, 9085, 18346, 382, 1519, 572, 5538, 304, 19950, 11, 264, 44250, 5426, 315, 3381, 18512, 29140, 23270, 11, 979, 279, 11285, 353, 9989, 9, 315, 264, 501, 2551, 10582, 37377, 5193, 806, 5244, 13, 1260, 66314, 279, 32047, 311, 7069, 1779, 432, 11, 96358, 37543, 311, 279, 4516, 315, 806, 4522, 13, 34172, 2677, 4829, 2494, 13, 1084, 572, 264, 6783, 80590, 315, 7388, 323, 18154, 11, 264, 59035, 41938, 22266, 1435, 1212, 13, 576, 16334, 330, 14990, 1, 476, 279, 53457, 330, 5987, 601, 369, 15786, 1, 9324, 1075, 98416, 315, 264, 553, 45596, 11385, 11, 264, 882, 979, 22011, 3633, 5710, 944, 77826, 553, 7377, 7611, 382, 23949, 11, 279, 5426, 315, 3381, 8643, 1181, 9106, 11, 279, 4522, 63468, 1506, 151643]}

## metrics

In [9]:
import evaluate
import torch
import numpy as np
import re
from tqdm import tqdm

def generate_texts_from_model(model, dataset, max_length=2048):
    """Generate texts while preserving alignment with reference stories"""
    model.eval()
    results = []

    # small_dataset = dataset.select(range(2))  
    
    for sample in tqdm(dataset, desc="Generating stories"):
        prompt_text = f"""You are a creative writer specializing in short story writing. Generate a story based on the given details with minimum 1000 words. Only output the story!

        ### Input:
        Story prompt (topic/idea): {sample["prompt"]}
        Story theme: {sample["theme"]}

        ### Response:
        """
        
        inputs = tokenizer(prompt_text, return_tensors="pt", truncation=True, max_length=max_length).to("cuda")
        
        with torch.no_grad():
            output = model.generate(
                input_ids=inputs["input_ids"],
                max_new_tokens=max_length,
                do_sample=True,
                top_p=0.9,
                temperature=1.5,
                repetition_penalty=1.2,
                pad_token_id=tokenizer.eos_token_id,
                attention_mask=inputs["attention_mask"],
            )
        
        generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
        cleaned_text = clean_generated_text(generated_text)
        
        results.append({
            "generated_text": cleaned_text,
            "reference_text": sample["story"],
            "prompt": sample["prompt"],
            "theme": sample["theme"]
        })

    return results

def clean_generated_text(text):
    """Clean generated text by removing prompt artifacts"""
    # Remove everything before the actual story
    cleaned_text = re.sub(r".*?</think>", "", text, flags=re.DOTALL).strip()
    return cleaned_text.strip()

def evaluate_perplexity(model, generated_results):
    print("Evaluating perplexity")
    total_loss = 0
    num_samples = 0
    
    for result in generated_results:
        inputs = tokenizer(result["generated_text"], return_tensors="pt", truncation=True, max_length=512)
        inputs = {k: v.to("cuda") for k, v in inputs.items()}
        labels = inputs["input_ids"]

        with torch.no_grad():
            outputs = model(**inputs, labels=labels)
            loss = outputs.loss.item()

        total_loss += loss
        num_samples += 1

    return np.exp(total_loss / num_samples)

def evaluate_bleu(generated_results):
    print("Evaluating BLEU")
    bleu = evaluate.load("bleu")
    predictions = [res["generated_text"] for res in generated_results]
    references = [[res["reference_text"]] for res in generated_results]
    results = bleu.compute(predictions=predictions, references=references)
    return results["bleu"]

def evaluate_bertscore(generated_results):
    print("Evaluating BERTScore")
    bertscore = evaluate.load("bertscore")
    predictions = [res["generated_text"] for res in generated_results]
    references = [res["reference_text"] for res in generated_results]
    results = bertscore.compute(predictions=predictions, references=references, lang="en")
    return {
        "precision": np.mean(results["precision"]),
        "recall": np.mean(results["recall"]),
        "f1": np.mean(results["f1"])
    }

def evaluate_mauve(generated_results):
    print("Evaluating MAUVE")
    mauve = evaluate.load("mauve")
    predictions = [res["generated_text"] for res in generated_results]
    references = [res["reference_text"] for res in generated_results]
    results = mauve.compute(predictions=predictions, references=references)
    return results.mauve

def evaluate_distinct_n(generated_results, n=2):
    """Calculate Distinct-N metric (diversity of n-grams)"""
    print(f"Evaluating Distinct-{n}")
    generated_texts = [res["generated_text"] for res in generated_results]
    
    all_ngrams = set()
    total_ngrams = 0
    
    for text in generated_texts:
        tokens = text.split()
        ngrams = set(zip(*[tokens[i:] for i in range(n)]))
        all_ngrams.update(ngrams)
        total_ngrams += len(ngrams)
    
    return len(all_ngrams) / total_ngrams if total_ngrams > 0 else 0

def evaluate_repetition_n(generated_results, n=2):
    """Calculate Repetition-N metric (fraction of repeated n-grams)"""
    print(f"Evaluating Repetition-{n}")
    generated_texts = [res["generated_text"] for res in generated_results]
    
    repeated_ngrams = 0
    total_ngrams = 0
    
    for text in generated_texts:
        tokens = text.split()
        ngrams = list(zip(*[tokens[i:] for i in range(n)]))
        total_ngrams += len(ngrams)
        repeated = len(ngrams) - len(set(ngrams))
        repeated_ngrams += max(0, repeated)

    return repeated_ngrams / total_ngrams if total_ngrams > 0 else 0

def run_full_evaluation(model, dataset):
    """Complete evaluation pipeline with separated metrics"""
    # 1. Generate aligned texts
    generation_results = generate_texts_from_model(model, dataset)
    
    # 2. Run all evaluations
    metrics = {
        "perplexity": evaluate_perplexity(model, generation_results),
        "bleu": evaluate_bleu(generation_results),
        "bertscore": evaluate_bertscore(generation_results),
        "mauve": evaluate_mauve(generation_results),
        "distinct_4": evaluate_distinct_n(generation_results, n=4),
        "repetition_4": evaluate_repetition_n(generation_results, n=4),
    }
    
    # 3. Add metadata
    metrics.update({
        "num_samples": len(generation_results),
        "avg_length": np.mean([len(res["generated_text"].split()) for res in generation_results])
    })
    
    return metrics, generation_results

## study

In [10]:
def get_num_layers(model):
    numbers = set()
    for name, _ in model.named_parameters():
        for number in re.findall(r'\d+', name):
            numbers.add(int(number))
    return max(numbers)

def get_last_layer_linears(model):
    names = []
    
    num_layers = get_num_layers(model)
    for name, module in model.named_modules():
        if str(num_layers) in name and not "encoder" in name:
            if isinstance(module, torch.nn.Linear):
                names.append(name)
    return names

In [11]:
def objective(trial):    
    global start_time
    if time.time() - start_time > TIME_LIMIT:
        raise optuna.exceptions.TrialPruned()

    torch.cuda.empty_cache()

    # Hyperparameter search space
    lora_r = trial.suggest_categorical('r', [8, 16])
    lora_alpha = trial.suggest_categorical('alpha', [16, 32])
    dropout = trial.suggest_categorical('dropout', [0.0, 0.1])
    learning_rate = trial.suggest_categorical('learning_rate', [1e-4, 2e-5, 5e-5, 1e-6])
    batch_size = trial.suggest_categorical('batch_size', [1, 2, 4])
    grad_accum_steps = trial.suggest_categorical('grad_accum_steps', [4, 8])
    num_epochs = trial.suggest_int('num_epochs', 1, 5)

    if batch_size * grad_accum_steps > len(tokenized_train_dataset):
        raise optuna.exceptions.TrialPruned()

    if lora_alpha == lora_r:
        raise optuna.exceptions.TrialPruned()

    print(f"Trial {trial.number} sedang berjalan dengan parameter:")
    print(f"  r={lora_r}, alpha={lora_alpha}, dropout={dropout}, learning_rate={learning_rate}, batch_size={batch_size}, grad_accum_steps={grad_accum_steps}, num_epochs={num_epochs}")

    # Setup LoRA configuration
    config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        target_modules=get_last_layer_linears(base_model),
        bias="none",
        lora_dropout=dropout,
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(base_model, config)

    training_args = TrainingArguments(
        output_dir=f"./optuna_trial_{trial.number}",
        warmup_ratio=0.1,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=grad_accum_steps,
        num_train_epochs=num_epochs,
        learning_rate=learning_rate,
        logging_steps=100,
        fp16=True,
        optim="paged_adamw_8bit",
        logging_dir="./logs",
        report_to='none',
    )

    trainer = Trainer(
        model=model,
        train_dataset=tokenized_train_dataset,
        eval_dataset=tokenized_val_dataset,
        args=training_args,
        data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )

    model.config.use_cache = False
    trainer.train()
    eval_result = trainer.evaluate()

    try:
        # Try full evaluation
        metrics, results = run_full_evaluation(model, tokenized_sampled_val_dataset)

        # Store all metrics
        trial.set_user_attr("eval_loss", float(eval_result["eval_loss"]))
        trial.set_user_attr("perplexity", float(metrics["perplexity"]))
        trial.set_user_attr("bertscore_f1", float(metrics["bertscore"]["f1"]))
        for k, v in metrics.items():
            if k not in ["perplexity", "bertscore"]:
                trial.set_user_attr(k, v)

        # Objective score
        score = (metrics["mauve"] + metrics["distinct_4"] + metrics["bleu"]) - (eval_result["eval_loss"] + metrics["repetition_4"])

        # Print results
        print(f"Metrics: {metrics}")

        # Sample output
        print("\n=== Sample Generation ===")
        for i, res in enumerate(results[:2]):
            print(f"\nSample {i+1} (Prompt: {res['prompt'][:50]}...)")
            print(f"Generated: {res['generated_text'][:100]}...")
            print(f"Reference: {res['reference_text'][:100]}...")

        # Save output
        os.makedirs("trial_outputs", exist_ok=True)
        save_generated_text(metrics, results, f"trial_outputs/trial_{trial.number}.json")
    except Exception as e:
        print(f"\n⚠️ Evaluation failed: {e}")
        score = -eval_result["eval_loss"]
        trial.set_user_attr("eval_loss", float(eval_result["eval_loss"]))

    del model
    torch.cuda.empty_cache()

    return score

In [12]:
def save_generated_text(metrics, results, filename='trial_outputs/generated.json'):
    output_data = dict(metrics)
    output_data["samples"] = results
    
    # Write results to JSON
    with open(filename, mode='w', encoding='utf-8') as f:
        json.dump(output_data, f, indent=2, ensure_ascii=False)

    print("generated text saved successfully.")

In [13]:
def save_study(study, filename='/kaggle/working/optuna_study.pkl'):
    with open(filename, 'wb') as f:
        pickle.dump(study, f)
    print("Study saved successfully.")

def save_callback(study, trial):
    save_study(study)

In [14]:
def print_trials(path):
    with open(path, 'rb') as f:
        study = pickle.load(f)

    # Tampilkan informasi umum tentang studi
    print("Study name:", study.study_name)
    print("Number of trials:", len(study.trials))
    
    # Tampilkan trial terbaik
    print("Best trial:")
    print("  Value:", study.best_trial.value)
    print("  Params:", study.best_trial.params)
    
    # Tampilkan semua trials
    for trial in study.trials:
        print(f"Trial {trial.number}:")
        print(f"  Params: {trial.params}")
        print(f"  Value: {trial.value}")
        print(f"  Attributes: {trial.user_attrs}")

In [ ]:
base_model = base_model.to('cuda').train()

TIME_LIMIT = 11 * 3600
start_time = time.time()

study_path = '/kaggle/input/dr1-q7b-optstudy/optuna_study.pkl'

# Muat hasil optuna sebelumnya jika ada
try:
    with open(study_path, 'rb') as f:
        study = pickle.load(f)
    print("Loaded existing Optuna study.")
    print_trials(study_path)
except FileNotFoundError:
    study = optuna.create_study(study_name="deepseek-r1-qwen7b-wp", direction="maximize", pruner=MedianPruner(n_warmup_steps=5))

try:
    study.optimize(objective, timeout=TIME_LIMIT, callbacks=[save_callback],)
except (KeyboardInterrupt, optuna.exceptions.TrialPruned, Exception) as e:
    print(f"Training berhenti karena: {e}")
    save_study(study)

print("Best trial:", study.best_trial.params)

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

Loaded existing Optuna study.
Study name: deepseek-r1-qwen7b-wp
Number of trials: 21
Best trial:
  Value: -0.7267189552619016
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 4, 'num_epochs': 1}
Trial 0:
  Params: {'r': 8, 'alpha': 16, 'dropout': 0.1, 'learning_rate': 5e-05, 'batch_size': 4, 'grad_accum_steps': 8, 'num_epochs': 3}
  Value: -1.6725816884497253
  Attributes: {'eval_loss': 3.00537109375, 'perplexity': 108.14976100376238, 'bertscore_f1': 0.7844989517560372, 'bleu': 0.002128327161689148, 'mauve': 0.33234759042886697, 'distinct_4': 0.9984222838800936, 'repetition_4': 0.0001087961703748028, 'num_samples': 52, 'avg_length': 710.0384615384615}
Trial 1:
  Params: {'r': 8, 'alpha': 16, 'dropout': 0.0, 'learning_rate': 1e-06, 'batch_size': 2, 'grad_accum_steps': 4, 'num_epochs': 3}
  Value: -2.4723002976009756
  Attributes: {'eval_loss': 3.8031415939331055, 'perplexity': 73.08005287982864, 'bertscore_f1': 0.7922788789639106, 'bleu': 0.0022410123153842804, 'mauve': 0.32876327803578775, 'distinct_4': 0.9998641710358317, 'repetition_4': 2.7165054873410843e-05, 'num_samples': 52, 'avg_length': 710.9230769230769}
Trial 2:
  Params: {'r': 16, 'alpha': 32, 'dropout': 0.0, 'learning_rate': 2e-05, 'batch_size': 4, 'grad_accum_steps': 8, 'num_epochs': 2}
  Value: -1.9349306276533569
  Attributes: {'perplexity': 114.8853555716292, 'bleu': 0.0018602800760038594, 'bertscore': {'precision': 0.7732126460625575, 'recall': 0.7894732894805762, 'f1': 0.7811346191626328}, 'mauve': 0.3315432031471034, 'distinct_4': 0.9998844064270026, 'repetition_4': 0.0, 'num_samples': 52, 'avg_length': 668.4615384615385}
Trial 3:
  Params: {'r': 16, 'alpha': 32, 'dropout': 0.0, 'learning_rate': 2e-05, 'batch_size': 4, 'grad_accum_steps': 8, 'num_epochs': 2}
  Value: -1.8543264756957236
  Attributes: {'eval_loss': 3.0613815784454346, 'perplexity': 161.6623603740358, 'bertscore_f1': 0.7727430267975881, 'bleu': 0.001326548792595646, 'mauve': 0.20732605880668356, 'distinct_4': 0.9984024951504317, 'repetition_4': 0.0, 'num_samples': 52, 'avg_length': 508.5192307692308}
Trial 4:
  Params: {'r': 16, 'alpha': 16, 'dropout': 0.1, 'learning_rate': 5e-05, 'batch_size': 2, 'grad_accum_steps': 4, 'num_epochs': 3}
  Value: None
  Attributes: {}
Trial 5:
  Params: {'r': 16, 'alpha': 16, 'dropout': 0.0, 'learning_rate': 1e-06, 'batch_size': 1, 'grad_accum_steps': 8, 'num_epochs': 3}
  Value: None
  Attributes: {}
Trial 6:
  Params: {'r': 16, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 4, 'grad_accum_steps': 4, 'num_epochs': 1}
  Value: -1.4130110291165447
  Attributes: {'eval_loss': 3.0296530723571777, 'perplexity': 153.26435681139262, 'bertscore_f1': 0.7553291561511847, 'bleu': 0.0014369747586225382, 'mauve': 0.6152050684820105, 'distinct_4': 1.0, 'repetition_4': 0.0, 'num_samples': 52, 'avg_length': 647.3846153846154}
Trial 7:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 8, 'num_epochs': 3}
  Value: -0.8714831701070622
  Attributes: {'eval_loss': 2.73852276802063, 'perplexity': 249.50910658235665, 'bertscore_f1': 0.726161451293872, 'bleu': 0.0029129971367375255, 'mauve': 0.8701389504680881, 'distinct_4': 0.9939876503087423, 'repetition_4': 0.0, 'num_samples': 52, 'avg_length': 949.5384615384615}
Trial 8:
  Params: {'r': 16, 'alpha': 16, 'dropout': 0.1, 'learning_rate': 5e-05, 'batch_size': 4, 'grad_accum_steps': 8, 'num_epochs': 3}
  Value: None
  Attributes: {}
Trial 9:
  Params: {'r': 8, 'alpha': 16, 'dropout': 0.0, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 8, 'num_epochs': 2}
  Value: -1.2800511927686697
  Attributes: {'eval_loss': 2.880815029144287, 'perplexity': 134.88720405832345, 'bertscore_f1': 0.7744239110213059, 'bleu': 0.0039570147849912725, 'mauve': 0.6019161870302655, 'distinct_4': 0.994952189436533, 'repetition_4': 6.155487617210743e-05, 'num_samples': 52, 'avg_length': 940.1923076923077}
Trial 10:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 4, 'num_epochs': 1}
  Value: -0.8775531177230473
  Attributes: {'eval_loss': 2.7858798503875732, 'perplexity': 131.9724267849026, 'bertscore_f1': 0.7711111742716569, 'bleu': 0.003449139151757033, 'mauve': 0.9106816632249941, 'distinct_4': 0.9943308908600077, 'repetition_4': 0.00013496057223282628, 'num_samples': 52, 'avg_length': 1000.3846153846154}
Trial 11:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 4, 'num_epochs': 1}
  Value: -0.7267189552619016
  Attributes: {'eval_loss': 2.7053616046905518, 'perplexity': 159.17979695408684, 'bertscore_f1': 0.7417813012233148, 'bleu': 0.004379560531907385, 'mauve': 0.980741765479099, 'distinct_4': 0.9936016976400232, 'repetition_4': 8.037422237939848e-05, 'num_samples': 52, 'avg_length': 1199.1538461538462}
Trial 12:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 4, 'num_epochs': 1}
  Value: -1.2916931714568831
  Attributes: {'eval_loss': 2.868894338607788, 'perplexity': 110.92154340911432, 'bertscore_f1': 0.7886301703177966, 'bleu': 0.0020300712761430074, 'mauve': 0.5802447202085989, 'distinct_4': 0.9950979190666438, 'repetition_4': 0.00017154340048032153, 'num_samples': 52, 'avg_length': 787.7307692307693}
Trial 13:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 4, 'num_epochs': 2}
  Value: -1.2590584693767586
  Attributes: {'eval_loss': 2.711559295654297, 'perplexity': 96.97925947408935, 'bertscore_f1': 0.7832611203193665, 'bleu': 0.005257442585097516, 'mauve': 0.4574966313945146, 'distinct_4': 0.9897791982348838, 'repetition_4': 3.2445936957544495e-05, 'num_samples': 52, 'avg_length': 1188.4038461538462}
Trial 14:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 8, 'num_epochs': 1}
  Value: -1.6334293755719473
  Attributes: {'eval_loss': 2.930021286010742, 'perplexity': 132.25319026810203, 'bertscore_f1': 0.7868209057129346, 'bleu': 0.0018300860457331693, 'mauve': 0.2976247292776714, 'distinct_4': 0.997315996659907, 'repetition_4': 0.00017890154451666765, 'num_samples': 52, 'avg_length': 647.9615384615385}
Trial 15:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 4, 'num_epochs': 2}
  Value: -0.9070630382103104
  Attributes: {'eval_loss': 2.7177889347076416, 'perplexity': 150.83647682827484, 'bertscore_f1': 0.7549817539178408, 'bleu': 0.004143618701253238, 'mauve': 0.8172131420612403, 'distinct_4': 0.9895470947072054, 'repetition_4': 0.00017795897236782502, 'num_samples': 52, 'avg_length': 1191.576923076923}
Trial 16:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 2, 'grad_accum_steps': 4, 'num_epochs': 1}
  Value: -1.2802040383795992
  Attributes: {'eval_loss': 2.67559814453125, 'perplexity': 198.58609019852193, 'bertscore_f1': 0.7421150562854913, 'bleu': 0.004297295661144513, 'mauve': 0.40038005999485005, 'distinct_4': 0.9907510681744084, 'repetition_4': 3.43176787522092e-05, 'num_samples': 52, 'avg_length': 1123.576923076923}
Trial 17:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 1e-06, 'batch_size': 1, 'grad_accum_steps': 8, 'num_epochs': 2}
  Value: -2.11584976328413
  Attributes: {'eval_loss': 3.7360026836395264, 'perplexity': 77.09851614076327, 'bertscore_f1': 0.7875283371943694, 'bleu': 0.0020679132044415212, 'mauve': 0.6183867783742936, 'distinct_4': 0.9998079561042524, 'repetition_4': 0.00010972732759093652, 'num_samples': 52, 'avg_length': 704.0384615384615}
Trial 18:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 2e-05, 'batch_size': 1, 'grad_accum_steps': 4, 'num_epochs': 5}
  Value: -1.0730388535973736
  Attributes: {'eval_loss': 2.863450288772583, 'perplexity': 128.59649825364184, 'bertscore_f1': 0.7880800343476809, 'bleu': 0.0022681009494731554, 'mauve': 0.7890011353139182, 'distinct_4': 0.9991421989118181, 'repetition_4': 0.0, 'num_samples': 52, 'avg_length': 787.6538461538462}
Trial 19:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 8, 'num_epochs': 5}
  Value: -0.8211097270589158
  Attributes: {'eval_loss': 2.779296398162842, 'perplexity': 152.0220997391265, 'bertscore_f1': 0.758241531940607, 'bleu': 0.0026155359583378106, 'mauve': 0.959204122672331, 'distinct_4': 0.9963670124732572, 'repetition_4': 0.0, 'num_samples': 52, 'avg_length': 955.6923076923077}
Trial 20:
  Params: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 2, 'grad_accum_steps': 4, 'num_epochs': 5}
  Value: -1.1421995910193439
  Attributes: {'eval_loss': 2.7787413597106934, 'perplexity': 192.37159385914478, 'bertscore_f1': 0.7714653393396964, 'bleu': 0.0037449870297736583, 'mauve': 0.6395711448190864, 'distinct_4': 0.9938784270543662, 'repetition_4': 0.0006527902118770516, 'num_samples': 52, 'avg_length': 1034.0192307692307}
Trial 21 sedang berjalan dengan parameter:
  r=8, alpha=32, dropout=0.1, learning_rate=0.0001, batch_size=1, grad_accum_steps=8, num_epochs=4

Generating stories: 100%|██████████| 52/52 [1:38:50<00:00, 114.05s/it]

Evaluating perplexity
Evaluating BLEU

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

Evaluating BERTScore

Downloading builder script:   0%|          | 0.00/7.95k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

Evaluating MAUVE

Downloading builder script:   0%|          | 0.00/7.24k [00:00<?, ?B/s]

Loading tokenizer

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Tokenizing text...
Loading tokenizer
Loading model

model.safetensors:   0%|          | 0.00/3.25G [00:00<?, ?B/s]

Featurizing tokens

Featurizing p:   0%|          | 0/50 [00:00<?, ?it/s]

Tokenizing text...
Featurizing tokens

Featurizing q:   0%|          | 0/52 [00:00<?, ?it/s]

seed = 25
performing clustering in lower dimension = 66
kmeans time: 0.19 s
total discretization time: 0.25 seconds
Evaluating Distinct-4
Evaluating Repetition-4
Metrics: {'perplexity': 146.07223889610378, 'bleu': 0.001928608876736781, 'bertscore': {'precision': 0.7527332397607657, 'recall': 0.7615567205043939, 'f1': 0.7569972998820819}, 'mauve': 0.7087782222532548, 'distinct_4': 0.995668501685657, 'repetition_4': 6.400819304871024e-05, 'num_samples': 52, 'avg_length': 904.2115384615385}

=== Sample Generation ===

Sample 1 (Prompt: " So, you do know why we called you down here righ...)
Generated: ### Analysis:
This user submitted their final rewritten version of one fictional essay and wants cla...
Reference: Felix Bowman was wrestling with the final stages of a major project on a Tuesday afternoon that felt...

Sample 2 (Prompt: A game among aliens is to conquer other planets us...)
Generated: You are a creative writer specializing in short story writing. Generate a story based on the given d...
Reference: So, pray tell, Milyama Tresk al-Salmizar de Truyne inquired, what can I do about this? Well, replied...
generated text saved successfully.

[I 2025-04-22 16:26:27,668] Trial 21 finished with value: -1.0878485645985914 and parameters: {'r': 8, 'alpha': 32, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 1, 'grad_accum_steps': 8, 'num_epochs': 4}. Best is trial 11 with value: -0.7267189552619016.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

Study saved successfully.
Trial 22 sedang berjalan dengan parameter:
  r=8, alpha=32, dropout=0.1, learning_rate=0.0001, batch_size=1, grad_accum_steps=8, num_epochs=4

In [ ]:
# hajhsjah
zxzcf 
print()